# Generated by Django 3.2.3 on 2021-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_allgroups_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgroups',
            name='dob',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
    ]
