# Generated by Django 3.2.3 on 2021-06-13 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_allgroups_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default=datetime.datetime(2021, 6, 13, 10, 23, 44, 416040, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allgroups',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
