# Generated by Django 3.2.3 on 2021-06-17 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20210613_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='password',
            field=models.CharField(default=datetime.datetime(2021, 6, 17, 10, 53, 3, 519618, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allgroups',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 6, 17, 10, 53, 20, 173467, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='bg',
            field=models.CharField(default=datetime.datetime(2021, 6, 17, 10, 53, 32, 456161, tzinfo=utc), max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
