# Generated by Django 3.2.3 on 2021-07-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20210620_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pbloodgroup', models.CharField(max_length=100)),
                ('p_place', models.CharField(max_length=50)),
                ('p_mobile', models.CharField(max_length=10)),
                ('p_mail_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelTable(
            name='allgroups',
            table='calc_allgroups',
        ),
    ]
