# Generated by Django 3.2.3 on 2021-07-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20210703_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allpatients',
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
