# Generated by Django 3.2.3 on 2021-07-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20210706_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table=None,
        ),
    ]
