# Generated by Django 3.2.3 on 2021-07-06 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_alter_services_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='dmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='dname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='dmobile',
            new_name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='services',
            name='dtext',
        ),
        migrations.AddField(
            model_name='services',
            name='Comments',
            field=models.CharField(default=datetime.datetime(2021, 7, 6, 12, 34, 24, 889091, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='services',
            table='calc_services',
        ),
    ]
