# Generated by Django 3.2.3 on 2021-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20210706_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('patientBloodGroup', models.CharField(max_length=4)),
                ('hospitalName', models.CharField(max_length=200)),
                ('mobileNumber', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'calc_patient',
            },
        ),
        migrations.AlterField(
            model_name='allgroups',
            name='mail_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
