# Generated by Django 3.2.3 on 2021-07-25 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20210724_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 7, 25, 5, 31, 28, 515388, tzinfo=utc), upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
