# Generated by Django 3.2.3 on 2021-07-27 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20210727_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='age',
        ),
        migrations.AddField(
            model_name='allgroups',
            name='dob',
            field=models.CharField(default=datetime.datetime(2021, 7, 27, 7, 30, 31, 261593, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
