# Generated by Django 3.2.3 on 2021-08-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20210727_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
